FACEBOOK_CONSUMER_KEY = [replace me]
FACEBOOK_CONSUMER_SECRET = [replace me]

TWITTER_CONSUMER_KEY = [replace me]
TWITTER_CONSUMER_SECRET = [replace me]

INSTAGRAM_CONSUMER_KEY = [replace me]
INSTAGRAM_CONSUMER_SECRET = [replace me]

WEIBO_CONSUMER_KEY = [replace me]
WEIBO_CONSUMER_SECRET = [replace me]